# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Text Input"
  description: Simple text input
  icon: create
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  placeholder: ""
  id:
  required: false
  helper_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Full name
  placeholder: John Smith

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  helper_text:
    comment: Helpful text for the user such as 'You do not need to enter your middle name(s)'
  id:
    _instance_value: UUID
    hidden: true    