# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Embed"
  description: A custom embed along with any extra information
  icon: web_asset
  tags: ['embed', 'media', 'document']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    show_note: true
    id:
    heading: bookshop:generic/heading!
    description: Description text to compliment the block
    embed: bookshop:generic/custom-embed!
    button: bookshop:generic/button
  styles:
    color_group: "primary"
    content_alignment: center

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  show_note: true

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  embed:
    comment: Copy the embed code from the chosen provider here. This approach is not recommended for youtube/vimeo (use the centered large asset component instead)