# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Section Heading"
  description: A heading for form sections
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: Form section
  

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: Form section

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: