# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Image Cards"
  description: A grid layout of cards with images
  icon: table_chart
  tags: ['grid', 'image']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    id:
    heading: bookshop:generic/heading!
    description: Description text to compliment the block
    grid_items:
      - image: bookshop:generic/image!
        heading:  bookshop:generic/heading!
        description: These versatile cards can be used to talk about your services or products, or anything else you are keen to share with your audience. They come with an action link to get your users into the journey you’ve crafted for them.
        buttons: [bookshop:generic/button]
    buttons: [bookshop:generic/button]
  styles:
    color_group: "primary"
    card_color_group: "primary"
    content_alignment: center

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    heading:
      _bookshop_name: generic/heading
      eyebrow_headline: Eyebrow Heading
      primary_heading: Primary Heading
    description: Card Grid Description
    grid_items:
      - image: bookshop:generic/image
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
      - image: bookshop:generic/image
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
      - image: bookshop:generic/image
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
    buttons:
      - _bookshop_name: generic/button
        url: "#"
        open_in_new_tab: false
        text: Button text
        variant: primary
        arrow: right
  styles:
    color_group: "primary"
    content_alignment: center
    card_color_group: "primary"
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:   
