# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Simple Text Block"
  description: Block of content with a header
  icon: article
  tags: ['text']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    id:
    heading: bookshop:generic/heading!
    text: bookshop:generic/text-block!
  styles:
    color_group: "primary"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
