# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Checkbox Group"
  description: Group of checkbox inputs
  icon: check_box
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id:
  checkboxes:
    - label:
      id:
      checked: false
      required: false
  arrangement: inline
  helper_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Checkbox group
  id: 915341d1-0f7f-4db1-bee6-3335435dfeda
  checkboxes:
    - label: Checkbox 1
      id: 0bb9d85c-017e-483c-bcb6-3cf842ba0468
      checked: true
      required: false
    - label: Checkbox 2
      id: bd126f91-44da-4de0-a371-fd08a711efb4
      checked: false
      required: false
    - label: Checkbox 3
      id: fa24b997-f0c0-46eb-b7d0-02b4b5aa2e1e
      checked: false
      required: false
  helper_text: Optional helper text

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    _instance_value: UUID
    hidden: true
  label:
    comment: It is recommended to provide a label for this input group
  helper_text:
    comment: Helpful text for the user such as 'Do not select more than 2'
