# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Image Gallery"
  description: A grid layout of images
  icon: collections
  tags: ['grid', 'image']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    show_note: true
    id:
    heading: bookshop:generic/heading!
    description: Description text to compliment the block
    gallery: bookshop:simple/image-gallery!
  styles:
    color_group: "primary"
    content_alignment: center

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    show_note: true
    heading:
      _bookshop_name: generic/heading
      eyebrow_headline: EYEBROW HEADLINE
      primary_heading: List your services and products
    description: >-
      Whether your business is a restaurant, a barber shop, a gym, or a café, our
      small business template has you covered. Add your services to the list
      below, as many as you like, and let people contact you or book now.
    gallery: bookshop:simple/image-gallery
  styles:
    color_group: "primary"
    content_alignment: center

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:    
