# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Social Icons"
  description: Icon links to social media platforms
  icon: share
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  show_note: true
  social_media_links:
    - link_url: https://www.youtube.com/
      icon_path: /assets/images/icons/social/youtube.svg
      label: Youtube
    - link_url: https://www.facebook.com/
      icon_path: /assets/images/icons/social/facebook.svg
      label: Facebook
    - link_url: https://www.linkedin.com/
      icon_path: /assets/images/icons/social/linkedin.svg
      label: LinekdIn
    - link_url: https://www.twitter.com/
      icon_path: /assets/images/icons/social/x.svg
      label: Twitter
    - link_url: https://www.instagram.com/
      icon_path: /assets/images/icons/social/instagram.svg
      label: Instagram
  style:
    icon_background_hover_color: "#7d7f7c"
    icon_color: "#7d7f7c"
    icon_hover_color: "#000000"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  show_note: true
  social_media_links:
    - link_url: https://www.youtube.com/
      icon_path: /assets/images/icons/social/youtube.svg
      label: Youtube
    - link_url: https://www.facebook.com/
      icon_path: /assets/images/icons/social/facebook.svg
      label: Facebook
    - link_url: https://www.linkedin.com/
      icon_path: /assets/images/icons/social/linkedin.svg
      label: LinekdIn
    - link_url: https://www.twitter.com/
      icon_path: /assets/images/icons/social/x.svg
      label: Twitter
    - link_url: https://www.instagram.com/
      icon_path: /assets/images/icons/social/instagram.svg
      label: Instagram

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: This is a hidden accesibility label used by screen readers to describe what the link is
  social_media_links:
    type: array
    options:
      structures:
        values:
          - label: Social Media Link
            icon: link
            value:
              link_url:
              icon_path:
            _inputs:
              icon_path:
                type: image
                comment: This input is restricted to only allow images with type SVG
                options:
                  accepts_mime_types:
                    - image/svg+xml
