# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Helper text"
  description: Display a short explanatory text for a field
  icon: information-circle
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  helper_text: Helper text
  id:


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  helper_text: Helper text

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    hidden: true