# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Checkbox Input"
  description: A single checkbox input
  icon: check_box
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  group_name:
  label: 
  id:
  checked: false
  required: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "Checkbox"
  group_name: group-name
  id: cd105250-17cd-4303-85d0-2cdf2e83e1e1

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    _instance_value: UUID
    hidden: true