# Metadata about this component, to be used in the CMS
spec:
  structures:
    - card_imagery_blocks
    - icon_blocks
  label: "Hero Library Icon"
  description: An icon (from https://heroicons.com/) with an optional border and customisable color
  icon: bolt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  hero_library_icon_name: academic-cap
  icon_size: small
  icon_type: solid
  rounded_border: false
  theme_color: false
  color: "#7d7f7c"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  theme_color:
    comment: Use your theme color for the icon color and the rounded border color (if one is included)
    type: checkbox