# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Time Input"
  description: Time selection input
  icon: alarm
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  placeholder: ""
  id:
  helper_text:
  min:
  max:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Choose a time slot
  placeholder: 15:00
  min: 09:00
  max: 17:00

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  helper_text:
    comment: Helpful text for the user such as 'Pick a time between 9:00 and 17:00'
  min:
    type: time
  max:
    type: time
  id:
    _instance_value: UUID
    hidden: true