# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Card Grid"
  description: "A reusable card grid that can take in icons or an image as the card header"
  icon: table_chart
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    id:
    heading: bookshop:generic/heading
    description: Description text to compliment the block
    grid_items: [bookshop:generic/card]
    buttons: [bookshop:generic/button]
  styles:
    color_group: "primary"
    card_color_group: "primary"
    content_alignment: center

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    heading:
      _bookshop_name: generic/heading
      eyebrow_headline: Eyebrow Heading
      primary_heading: Primary Heading
    description: Card Grid Description
    grid_items:
      - bookshop:generic/card
      - bookshop:generic/card
      - bookshop:generic/card
    buttons:
      - _bookshop_name: generic/button
        url: "#"
        open_in_new_tab: false
        text: Button text
        variant: primary
        arrow: right
  styles:
    color_group: "primary"
    content_alignment: center
    card_color_group: "primary"
# Any extra CloudCannon inputs configuration to apply to the blueprint
