base_url: http://example.com
social_media_links:
  - link_url: https://www.youtube.com/
    icon_path: /assets/images/icons/social/youtube.svg
    label: YouTube
  - link_url: https://www.facebook.com/
    icon_path: /assets/images/icons/social/facebook.svg
    label: Facebook
  - link_url: https://www.linkedin.com/
    icon_path: /assets/images/icons/social/linkedin.svg
    label: LinkedIn
  - link_url: https://www.twitter.com/
    icon_path: /assets/images/icons/social/x.svg
    label: Twitter
  - link_url: https://www.instagram.com/
    icon_path: /assets/images/icons/social/instagram.svg
    label: Instagram
