# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Date Input"
  description: Calendar date picker input
  icon: date_range
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id:
  required: false
  min_today: false
  min:
  max_today: false
  max:
  helper_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Choose a date

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  helper_text:
    comment: Helpful text for the user such as 'The date should be after today'
  min:
    hidden: min_today
    comment: Select the earliest date a user is allowed to input (if not the current day)
    type: date
  max:
    hidden: max_today
    comment: Select the latest date a user is allowed to input (if not the current day)
    type: date
  min_today:
    type: switch
    comment: On if the earliest date to be selected should always be the current date
  max_today:
    type: switch
    comment: On if the latest date to be selected should always be the current date
  id:
    _instance_value: UUID
    hidden: true